### ISSUE TITLE
Class code 'NA' when it should be '='?

### ISSUE THREAD

**Issue by zoewardnz** [gpertea/gffcompare#26]
I have run stringtie merge and I then use stringtie_merged.gtf to compare to the latest version of the gencode annotation with gffcompare. All of the files should be formatted the same (i.e. both files have 'chr1') and I mapped the data with the same gencode annotation file.
`gffcompare -r gencode.v27.primary_assembly.annotation.gtf -o gff stringtie_merged.gtf`
There are ~ 1000 (<1%) of transcripts that are not being given a class code. 
For example when I create a transcript count matrix (with prepDE.py) transcript ENST00000640668.1 has read counts for all samples in the transcript count matrix but has no class code. When I search for this transcript in stringtie merged.gtf and look at each exon of this transcript and compare it to the genocde.gtf all of the co-ordinates exactly match so should gffcompare be giving it an '=' class code???
I have attached my stringtie_merged.gtf if this help to troubleshoot.
[stringtie_merged.gtf.gz](https://github.com/gpertea/gffcompare/files/1657741/stringtie_merged.gtf.gz)

**Comment by gpertea** [comment]
Thank you for the file, I see what's happening -- in the stringtie_merged.gtf file there are transcripts seen as "redundant" by gffcompare, in the sense that they have exactly the same intron-exon structure (specifically the same introns; the terminal exons may extend a bit differently). However gffcompare should NOT discard the duplicates -- and this is a long standing bug already reported in issue #18 which I still have to fix in gffcompare.

So you could not find the class code for ENST00000640668.1 because it was superseded by the duplicate transcript ENST00000396821.7 which gffcompare reports as having the class code ```=``` as expected. 

Even though I admit this being a bug in gffcompare (discarding the "redundant" transcript when in fact it should just assign a class code as required), I am wondering why did the Gencode annotation file include both of these redundant transcripts in the first place.. (because that's why they ended up as separate entries in the stringtie_merged file).

**Comment by gpertea** [comment]
I just patched gffcompare (and released version 0.10.2) to no longer discard redundant transcripts from the input when running in "annotation mode" (i.e. when a single input file is given and ```*.annotated.gtf``` file is being produced). The updated download links for this version are here:
https://ccb.jhu.edu/software/stringtie/gffcompare.shtml#gffcompare_dl

Please try this 0.10.2 version and let me know if it fixed the problem for you.

**Comment by zoewardnz** [comment]
I'm using the same command as above. and it's throwing an error?? 
```
line 11: syntax error near unexpected token `|'
line 11: `    {-i <input_gtf_list> | <input1.gtf> [<input2.gtf> .. <inputN.gtf>]}\n\'
```

**Comment by gpertea** [comment]
Which file did you download? Are you building the source package or using the pre-compiled binary packed in gffcompare-0.10.2.Linux_x86_64.tar.gz ? 

Because the error messages you're showing above makes it look as if you are trying to run the gffcompare.cpp source file directly as some sort of script in your shell.. Which would be mostly unusual..

**Comment by zoewardnz** [comment]
Yes, my mistake - I downloaded the wrong file. 
I ran the correct one and yes it has fixed the problem. Thanks very much for all of your help.
