### ISSUE TITLE
What's the mean of class code 'k'

### ISSUE THREAD

**Issue by Trandamere** [gpertea/gffcompare#27]
Hi:
 I can't find the class code k in cuffcompare.So,what's the mean of class code 'k'?

**Comment by gpertea** [comment]
I updated the documentation with some info about these new class codes -- please note that the official GffCompare documentation and download location is:
http://ccb.jhu.edu/software/stringtie/gffcompare.shtml

**Comment by bioinfomagician** [comment]
I found a definition for class code k here: https://ccb.jhu.edu/software/stringtie/gffcompare.shtml#transfrag-class-codes

It looks like it means that the reference transcript is contained completely within the transfrag (basically 'c' except the reference is contained in the transfrag rather than the opposite).

**Comment by bioinfomagician** [comment]
Oh, looks like I was beaten to answering here. 👍

**Comment by gpertea** [comment]
Thank you anyway for trying to help, Bioinfomagician (really cool stage name!).

**Comment by Trandamere** [comment]
Thank you!
