### ISSUE TITLE
Warning: reference transcript  has undetermined strand, discarded.

### ISSUE THREAD

**Issue by wangdepin** [gpertea/gffcompare#31]
Error while executing the below command
gffcompare  -V -R -r merged.gtf  -o gffcompare_output  -i gtf_list
Error happen: Warning: reference transcript  has undetermined strand, discarded.

merged.gtf comes form the output of stringtie --merge 
gtf_list is a list of  gtf files of 12 samples which are input file of stringtie --merge

**Comment by gpertea** [comment]
Sorry I'm very late getting to this, but..
That was a warning, not an error, right? At most we could say it was an user error I guess :)
Because why would one use gffcompare like this? gffcompare was obviously made to work with an actual reference annotation data for the -r parameter, and those should not include transcripts of undetermined strand.. If you still want to use it with a computationally derived "reference" which is so imperfect, then having those single exon transcripts discarded because they don't have a strand assigned should *not* be a real loss, right?
