### ISSUE TITLE
gff compare gives identical results for multiple files

### ISSUE THREAD

**Issue by jstrohm** [gpertea/gffcompare#6]
Hi there,

I'm doing something weird but I can't find my mistake. I'm running gff compare v 0.9.8.Linux_x86_64.
I have 16 stringtie assemblies, but when I run gff compare on the individual assemblies, I get identical results in the  .stats files. However, the file paths indicate that I have correctly provided different .gtf files. If I run multiple assemblies at once, the .stats file only contains the command run.

The reference genome is Atlantic salmon (Salmo salar). I'm also very skeptical that I have 100% sensitivity and precision. 

Here are the contents of a stats file:

 gffcompare v0.9.8 | Command line was:
./gffcompare -r /media/genetics/Data1/Jeff_workstation_1/subread-1.5.0-p1/GCF_000233375.1_ICSASG_v2_genomic.gff -o /media/genetics/Data1/Jeff_workstation_1/gffcompare-0.9.8.Linux_x86_64/compare/comp /media/genetics/Data1/Jeff_workstation_1/stringtie-1.3.1c.Linux_x86_64/outputs/assembled/11-B5690_S3_mRNA_ARGU1_NGSLib3b.gtf

= Summary for dataset: /media/genetics/Data1/Jeff_workstation_1/stringtie-1.3.1c.Linux_x86_64/outputs/assembled/11-B5690_S3_mRNA_ARGU1_NGSLib3b.gtf 
     Query mRNAs :  136272 in   81266 loci  (111377 multi-exon transcripts)
            (20690 multi-transcript loci, ~1.7 transcripts per locus)
 Reference mRNAs :  136039 in   81267 loci  (111148 multi-exon)
 Super-loci w/ reference transcripts:    80037
-----------------| Sensitivity | Precision  |
        Base level:   100.0     |   100.0    |
        Exon level:   100.0     |   100.0    |
      Intron level:    99.5     |    99.5    |
Intron chain level:   100.0     |    99.8    |
  Transcript level:   100.0     |    99.8    |
       Locus level:   100.0     |   100.0    |

     Matching intron chains:  111148
       Matching transcripts:  136039
              Matching loci:   81267

          Missed exons:       0/562650	(  0.0%)
           Novel exons:       0/562955	(  0.0%)
        Missed introns:    2190/471248	(  0.5%)
         Novel introns:       0/471248	(  0.0%)
           Missed loci:       0/81267	(  0.0%)
            Novel loci:       0/81266	(  0.0%)

 Total union super-loci across all input datasets: 81266

**Comment by gpertea** [comment]
How was that 11-B5690_S3_mRNA_ARGU1_NGSLib3b.gtf file generated? If it's directly by stringtie, the first line in the file should show the command line used by stringtie. Do you see a **-e** option in that stringtie command line, with -G pointing to the same reference file that you used for gffcompare here (GCF_000233375.1_ICSASG_v2_genomic.gff)  ? Because that would explain why you got 100% accuracy here..

If that's the case (I'm strongly hoping so) then I remind you that stringtie's -e option switches stringtie into "estimate-only" mode, so it won't try to assemble the read alignments at all, but only map them onto the given reference and spit out the exact same reference annotation transcripts (with renamed IDs, which may be confusing I guess..) but with expression estimates.. Of course gffcompare does not care about those estimates at all (i.e. doesn't care if they are zero or not) but only at the exon/intron structures of the given transcripts. gffcompare only cares about these structures -- it's specifically designed to assess the accuracy of transcript reconstruction (vs a reference data set), as it would be impossible to assess the accuracy of expression estimation (without providing a .bam file or some other similar coverage data).

Also, gffcompare would not compute accuracy stats when more than 6 input samples are provided at once (to save time/memory etc.) as it enters a "large scale" mode.

**Comment by jstrohm** [comment]
Awesome! Thank you yes I computed all of my assemblies with -e and -G enabled.
I misunderstood the usage of -e. Thanks for your detailed reply!

-Jeff

**Comment by gpertea** [comment]
Just to preempt a likely followup question: the missed introns there in the stats are very likely some aberrant micro-introns (?) that are sometimes present in annotation (for reasons still unfathomable to me) which the GFF parser discards when loading the file.. Running gffcompare with -V should show diagnostic messages about merging of adjacent exons.
