### ISSUE TITLE
Output path of refmap and tmap

### ISSUE THREAD

**Issue by culpinnis** [gpertea/gffcompare#8]
Hi,

This is only a very small issue, but I wanted to tell about it. 
It was not clear to me that the refmap and tmap is not written to the current directory, but in the directory of the GFF files. 
It is not a big deal, but I asked myself for about 2 hours why gffcompare generates all other files like .stats, .tracking and so on, but no tmap or refmap. 

Sorry for bothering with this issue.

Cheers
Chris

**Comment by gpertea** [comment]
No need to apologize, I agree this program still lacks the proper documentation for all its features. The decision to place those files in the same directory of the source GTF/GFF files was taken because they would otherwise clobber if they have the same file name -- imagine if all these input files are called something like this:
```
./sample1/transcripts.gtf
./sample2/transcripts.gtf
./sample3/transcripts.gtf
```
.. then just adding some prefix/suffix to the file name we would make the .tmap (or .refmap) files overwrite those from the other sample(s) if they were all written in the current directory.
