### ISSUE TITLE
GFFCompare ".tracking" file has zero value in<FPKM>|<TPM>|<cov> columns

### ISSUE THREAD

**Issue by Miracle-Yao** [gpertea/gffcompare#93]
Hello,
        When I compared single `merged.stringtie.assembly.gtf` (generated by stringtie merge function) file with known annotation gtf file, I found each line in <prefix>.tracking has zero value in  <FPKM>|<TPM>|<cov> columns，how can I got this information?
An example:
```
qJ:<gene_id>|<transcript_id>|<num_exons>|<FPKM>|<TPM>|<cov>|<len>
q1:MSTRG.1|MSTRG.1.1|3|0.000000|0.000000|0.000000|3357
```
Thanks

**Comment by santataRU** [comment]
Hi Yao,

I have the same issue as you. I used Gffcompare to identify novel transcripts between my cell-type-specific (HT-1080 cells) GTF annotation (generated by StringTie merge) and the hg38 GTF annotation from Ensembl. My FPKM and TPM columns show zero values. This makes sense, as we only provided two GTF annotations as input, and since FPKM and TPM information is not included in these files, the tool cannot compute these values.

Xiao

**Comment by Miracle-Yao** [comment]
Yes, @santataRU 
In fact, this is a `combined.gtf`. No `tpm` and `fpkm` information can be obtained from a single sample of `gtf` file, but software such as `featureCounts`, `rsem` can be used to for quantify counts and then convert to`tmp` or `fpkm`.
